creativecommons/vocabulary-theme

- src/footer.php
- src/header.php
* Fixes `vocabulary.css` inclusion in `header.php`. Moved to `@import` in `style.css`
* Fixes `vocabulary.js` inclusion in `footer.php`
* Adds current relevant nav items that were not properly synced from `creativecommons.org-prototype` in a previous PR, to the `header.php`
* Adds working links to `ancilliary-menu` (_To be changed to final links later_)
* Adds working links to `primary-nav` (_To be changed to final links later_)
index.md`).
<details> …
> link vocabulary JS and CSS correctly, add working nav items to primary-nav and ancilliary-menu

- src/functions.php
- src/inc/acf-json/group_64e6144d95eb4.json
- src/inc/acf-json/group_65047468148e1.json
- src/page-archive.php
- src/page_overview.php
- src/page_team.php
- src/search.php
- src/single-person.php
- src/style.css
* fix display of empty parenthesis around pronouns if not present
* setup baseline skeleton functionality and render for `overview-page` context, `page_overview.php`
* remove debug text in title on `page-archive.php`
* expand pagination to be 10 per page, on `archive-page` context
* add closing element to team-index
* add remaining sections to team-index, `page_team.php`
* add patch styles to `style.css` for better styling on past img insertion attachment markup
* ties searchform action to dynamic `home_url`, `search.php`
* bump version to `v0.11.0` in `style.css`
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source …
> prep `v0.11.0` release

- src/archive.php
- src/footer.php
- src/functions.php
- src/header.php
- src/inc/acf-json/group_650c88c50a218.json
- src/index.php
- src/page-archive.php
- src/page-blog.php
- src/page_blog.php
- src/page_home.php
- src/page_static.php
- src/page_team.php
- src/page_walkthrough.php
- src/search.php
- src/sidebar.php
- src/single-person.php
- src/singular.php
- src/static-templates/static-default.php
- src/style.css
- src/vocabulary/css/library-vars.css
- src/vocabulary/css/vendor/normalize.css
- src/vocabulary/css/vocabulary.css
- src/vocabulary/svg/font-awesome/icons/fa-icons.svg
* syncs changes from: 
- https://github.com/creativecommons/index-prototype/pull/35
- https://github.com/creativecommons/index-prototype/pull/36
- https://github.com/creativecommons/index-prototype/pull/37
* removes patches, now incorporated in `vocabulary.css`
* removes trailing whitespace
* adds new primary navigation locations
* adjusts rendered image sizes down
* outputs proper alt text on `home-index`
* fixes logic output of which items display in top highlight, recent posts, and attribution (was off by 1)
* adds `closing` element to the `blog-post` context, with adjoining fields, `singular.php`
* bumps version to `v0.14.0` in `style.css`
index.md`).
For the purposes of this DCO, …
> prep for `v0.14.0` release

- src/style.css
* add patch fixes to `style.css` for: 
- force position title to line wrap when name and/or title is short on `team-index` context
- correct top padding spacing of site `footer`
- correct position of `alignright` or `alignleft` set figure element in body, when `sidebar` is present, on `default-page` context
* bump version to `v0.16.0` in `style.css`
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```
> prep for `v0.16.0` release

- LICENSE
* update contents of `LICENSE` to GPLv2
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```
> correct LICENSE file

- README.md
Add cache warning to README
- New/PR [`README.md`](https://github.com/creativecommons/vocabulary-theme/blob/c9c634d5ea798e46644b954fd8ee691261a16509/README.md)
- Old/current [`README.md`](https://github.com/creativecommons/vocabulary-theme/blob/a9d72927acb0eab1a95c83aa99df96047b61448d/README.md)
index.md`).
<details>
```
Version 1.1 …
```
> Add cache warning to README

- src/style.css
* updates `style.css` with `v1.1`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> prep for `v1.1` release

- src/header.php
* fixes #40 
Due to the fact that the `Yoast SEO` plugin attempt to manipulate the site title, without a reliable way to disable it several route were tried to correct this behavior, which ultimately led to changing how the title is output itself. 
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> remove <title> duplication due to conflict with Yoast SEO plugin

- src/style.css
* updates version number in `style.css` to `v1.1.1`
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
> bump vocabulary-theme version to `v1.1.1` in `style.css`

- src/style.css
* fixes #44 
_**note:** below text is just placeholder for testing, the end-user can customize it to their choosing._
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
> add patch style for better button visual handling in top banner attention box

- src/style.css
* bumps version in `style.css` to `v1.2`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```
> bump version in `style.css` to `v1.2`

- src/style.css
* bumps version to `v1.3` in `style.css`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) …
```
> bump to `v1.3` in `style.css`

- src/feed-templates/feed-atom.php
- src/feed-templates/feed-rdf.php
- src/feed-templates/feed-rss.php
- src/feed-templates/feed-rss2.php
- src/functions.php
* fixes #36 
* creates appropriate functional overrides for the templates in `functions.php`
* adds new localized template overrides in `/feed-templates`, adjusts authorship output where appropriate
- `feed-atom.php`
- `feed-rdf.php`
- `feed-rss.php`
- `feed-rss2.php`
Outputs can be tested by navigating to the general or individual feed URLs
* `[localhost:8080]/feed`
* `[localhost:8080]/?feed=atom`
* `[localhost:8080]/?feed=rdf`
* `[localhost:8080]/?feed=rss`
* `[localhost:8080]/?feed=rss2`
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain …
> add `person(s)` authorship to `feed` templates

- src/style.css
* bumps `style.css` to `v1.3.1`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump `style.css` to `v1.3.1`

- src/functions.php
* Fixes #56 
* Adds a small filter function that _should_ disable the canonical redirect that's occurring when trying to create pagination on a single post page of a custom post type.
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```
> add override filter to stop redirect on Person post pagination

- src/style.css
* bumps `style.css` to `v1.3.2`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump `style.css` to `v1.3.2`

- src/style.css
* bumps `style.css` to `v1.3.3`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump `style.css` to `v1.3.3`

- src/page.php
Addresses:
* #72 
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
> remove legacy custom meta fields attached to old progam page templates

- src/style.css
* bumps `style.css` to `v1.4`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump `style.css` to `v1.4`

- src/footer.php
- Fixes #60
* Adds a simple `rel=me` attribute to the mastodon social link contained within `footer.php` that is rendered on each page.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
> add mastodon verification `rel=me` attribute to `footer.php`

- src/footer.php
- Fixes #77 by @TimidRobot 
This PR removes the publicly posted telephone number from the project as all legitimate contacts have alternative ways to reach .
The telephone number has been removed from `footer.php` file in `src `folder.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
> Feature : Removed telephone number from footer . 

- src/style.css
* bumps `style.css` to `v1.6`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump style.css to v1.6

- src/style.css
* bumps `style.css` to `v1.7`
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> bump `style.css` to `v1.7`

- .gitignore
- src/archive.php
- src/footer.php
- src/front-page-old.php
- src/header.php
- src/page-archive.php
- src/page-blog.php
- src/page-team.php
- src/page.php
- src/page_blog.php
- src/page_home.php
- src/search.php
- src/sidebar.php
- src/single-person.php
- src/single-program.php
- src/singular.php
- src/vocabulary/css/vocabulary.css
- src/vocabulary/js/vocabulary.js
incorporates relevant changes from the following upstream PRs:
- https://github.com/creativecommons/vocabulary/pull/50 
- https://github.com/creativecommons/vocabulary/pull/57
- https://github.com/creativecommons/vocabulary/pull/77
- https://github.com/creativecommons/vocabulary/pull/95
- https://github.com/creativecommons/vocabulary/pull/102 
- https://github.com/creativecommons/vocabulary/pull/136 
- https://github.com/creativecommons/vocabulary/pull/169
- https://github.com/creativecommons/vocabulary/pull/175
- https://github.com/creativecommons/vocabulary/pull/180
- https://github.com/creativecommons/vocabulary/pull/193
- https://github.com/creativecommons/vocabulary/pull/202
- https://github.com/creativecommons/vocabulary/pull/212
- …
> sync upstream `vocabulary` changes

- src/style.css
- src/vocabulary/js/vocabulary.js
- Includes changes from these upstream PRs:
- https://github.com/creativecommons/vocabulary/pull/328
- bumps `style.css` to `v1.8` (in preparation for new Release)
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
> update `vocabulary.js` to current, bump `style.css` to `v1.8`

- src/style.css
- src/vocabulary/css/vocabulary.css
implements upstream Vocabulary changes from:
- https://github.com/creativecommons/vocabulary/pull/334
- https://github.com/creativecommons/vocabulary/pull/338
Additionally: 
- updates version in `style.css` to `v1.9` to prep for release
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
> updated vocabulary to latest, prep for `v1.9` release

- src/page_home.php
- src/sidebar.php
- src/style.css
- Fixes #91 
- Fixes #92 
- updates `style.css` to `v1.9.1`
The theme had some gaps in the way it implements the newer `vocabulary` conventions, that should be corrected now. Specifically, the `topic-summary`, `case-studies` and `news` elements had incorrect set grid stylings, and the `sidebar.php` had missing double quotes on several attribute values
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```
> fix rendering issues, bump version to `v1.9.1` in `style.css`

- src/page-archive.php
- src/page_home.php
- src/sidebar.php
- src/style.css
Fixes several mistakes made in `v1.9.1`, involving syncing from incorrect source. I pulled directly from a specimen in `vocabulary` which is much more general, instead should have pulled from `index-prototype` to get the specific implementations required.
* the `sidebar.php` template is re-generalized, the specific classes are instead added to the `archive-page` context
* the `style.css` contains the correct local implementations, now sourced from `index-prototype`
* the `home-index` context (`page_home.php`), now sources its markup from `index-prototype`
* bump `style.css` to `v1.9.2`
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain …
> correct errrors caused by not using correct sourcing from `index-prototype`, bump version in `style.css` to `v1.9.2`

- src/archive.php
- src/page-archive.php
- src/page_blog.php
- src/style.css
* correctly adds the `sidebar` class to the remaining `asides`
* corrects `h2` to `h3` on `blog-index` context (`page_blog.php`)
* moves `more` `button` to within the `posts` `article` on `blog-index` context (`page_blog.php`)
* corrects styling for  smaller viewport wrapping on `home-index` context in the news area, by adjusting to match the blog-index approach (using `flex` over `grid`)
* tidies the `style.css` a bit, removing spacing and commented properties
* bumps `style.css` to `v1.9.3`
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain …
> correct post rendering errors on `home-index`,`blog-index`, `archive-page` contexts/templates, bump `style.css` to `v1.9.3`

- src/inc/acf-json/post_type_66e1db36db2a5.json
* sets correct property on `FAQ item` custom post type, so that while we are importing items they don't yet show up in the public search interface.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
> exclude `FAQ items` from search

- src/style.css
* bumps version in `style.css` to `v1.9.5` to prep for Release.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```
> bump version in `style.css` to `v1.9.5`

- src/style.css
* bumps version in `style.css` to `v1.10` to prep for Release.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
> bump version in `style.css` to `v1.10`

- src/style.css
* bumps version in `style.css` to `v1.11` to prep for Release.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
> bump `style.css` to `v1.11`

- docker/configs/composer.json
- docker/configs/composer.lock
* pulls relevant additional deps from `composer.json` in `index-dev-env` to make for better isolated testing
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
> update WordPress deps in `composer.json` for better baseline

- src/footer.php
* syncs from upstream Vocabulary, removes facebook icon from Global Footer
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```
> remove facebook icon from Global Footer

- src/style.css
* bumps version in `style.css` to `v1.13` to prep for Release.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
> bump `style.css` to `v1.13`

- src/chooser/css/chooser.css
- src/chooser/js/chooser.js
- src/static-templates/static-chooser.php
- update `chooser` to [`v1.2`](https://github.com/creativecommons/chooser/releases/tag/v1.2)
- cleanup trailing whitespace
one-line clean-up **macOS** command:
```bash
for _f in $(find * -type f -exec grep -I -q . {} \; -print); do sed -e's/[[:space:]]\+$//' -i '' "${_f}"; tail -c1 ${_f} | read -r \n || echo '' >> ${_f}; done
```
multi-line clean-up **macOS** command:
```bash
for _f in $(find * -type f -exec grep -I -q . {} \; -print)
do
sed -e's/[[:space:]]$\+//' -i '' "${_f}"
tail -c1 ${_f} | read -r \n || echo '' >> ${_f}
done
```
Notes:
- For Linux, replace the `-i ''` in the `sed` command with just `-i`
1. run the docker instance (and setup WP if not already)
2. create a page called "Chooser"
3. select template of "static"
4. enter "chooser" as `Static Template Name`
5. Save.
6. open …
> update `chooser` to `v1.2`
